### ISSUE TITLE
Prediction intervals

### ISSUE THREAD

**Issue by olangfor** [Keefe-Murphy/MoEClust#1]
Hi,

Just enquiring about the possibility of including prediction intervals?  Apologises if this is already available.

Thank you, for providing a great package.   Proving very useful and insightful.

**Comment by Keefe-Murphy** [comment]
Hi,

I'm glad you're finding the package useful!
Unfortunately, prediction intervals are not currently available, nor is it straightforward to implement them.

As mixtures fit via the EM algorithm don't readily produce standard errors, in particular for the cluster membership probabilities, there would be a lot of work involved in producing prediction intervals with the correct coverage. 

Though each $expert component of a MoE_clust fit is of class "lm", it would be wrong to produce prediction intervals (or even confidence intervals) directly from these lm fits, as doing so would be to assume that the group-memberships are fixed/known, rather than estimated. 

Thus, I didn't exclude code implementing this naive approach, as I didn't want to mislead users of the package. & I didn't include the proper/more-sophisticated approach because I'm not 100% sure of the correct way to go about doing so. For sure some bootstrap resampling would be involved, but I don't know precisely.

I'm sorry I couldn't be of more help!

Cheers,
Keefe

**Comment by olangfor** [comment]
Thank you Keefe,

I tried the naive approach and agree that it is misleading.  I also tried the bootstrap method and this seems more appropriate. I had already wrapped MoE in the tidymodels framework so I was to follow [this](https://www.bryanshalloway.com/2021/04/05/simulating-prediction-intervals/) implementation of the bootstrap prediction intervals.  Seems reasonable but I've yet to go through the details of the code.  I think I will go down the the bootstrap prediction intervals in the tidymodels framework so we are able to obtain prediction intervals from any regression model.  

Thanks again!
